
services:
  # Aplicación principal WPA
  wpa:
    build:
      context: ../WPA
      dockerfile: Dockerfile
    container_name: wpa-app
    restart: unless-stopped
    volumes:
      - static_files:/app/staticfiles
      - media_files:/app/media
      - logs:/app/logs
    environment:
      - DJANGO_SETTINGS_MODULE=coreapp.settings
      - DJANGO_ENV=production
      - DATABASE_URL=postgresql://wpa_user:${POSTGRES_PASSWORD:-wpa_secure_password_2025}@postgres:5432/wpa_db
    ports:
      - "8000:8000"
    networks:
      - wpa-network
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/')"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Base de datos PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: wpa-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: wpa_db
      POSTGRES_USER: wpa_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-wpa_secure_password_2025}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    networks:
      - wpa-network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wpa_user -d wpa_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Nginx como proxy reverso
  nginx:
    image: nginx:alpine
    container_name: wpa-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled:ro
      - static_files:/var/www/static:ro
      - media_files:/var/www/media:ro
      - ./ssl:/etc/nginx/ssl:ro
      - nginx_logs:/var/log/nginx
    networks:
      - wpa-network
    depends_on:
      wpa:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  wpa-network:
    driver: bridge

volumes:
  postgres_data:
  static_files:
  media_files:
  logs:
  nginx_logs:
