
services:
  # Aplicación principal WPA
  wpa:
    build:
      context: ../wpa
      dockerfile: Dockerfile
    container_name: wpa-app
    restart: unless-stopped
    volumes:
      - db_data:/app/db_data
      - static_files:/app/staticfiles
      - media_files:/app/media
      - logs:/app/logs
    environment:
      - DJANGO_SETTINGS_MODULE=coreapp.settings
      - DJANGO_ENV=production
    ports:
      - "8000:8000"
    networks:
      - wpa-network
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Base de datos PostgreSQL para producción
  postgres:
    image: postgres:15-alpine
    container_name: wpa-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: wpa_db
      POSTGRES_USER: wpa_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-wpa_secure_password_2025}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    networks:
      - wpa-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wpa_user -d wpa_db"]
      interval: 10s
      timeout: 5s
      retries: 5


  # Nginx como proxy reverso
  nginx:
    image: nginx:alpine
    container_name: wpa-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled:ro
      - static_files:/var/www/static:ro
      - media_files:/var/www/media:ro
      - ./ssl:/etc/nginx/ssl:ro
      - nginx_logs:/var/log/nginx
    networks:
      - wpa-network
    depends_on:
      - wpa
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3


  # Watchtower para actualizaciones automáticas

  # Grafana para dashboards de monitoreo

  # Prometheus para métricas

networks:
  wpa-network:
    driver: bridge

volumes:
  db_data:
  postgres_data:
  static_files:
  media_files:
  logs:
  nginx_logs:
