apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wpa
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/cgaviria92/infrastructure'
    targetRevision: main
    path: k8s/wpa
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
